apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tap-build
spec:
  settings:
    storage:
      defaultClass: tanzu
  topology:
    controlPlane:
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      replicas: 1
      storageClass: tanzu
      vmClass: best-effort-medium
    nodePools:
    - name: default-nodepool
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      replicas: 3
      storageClass: tanzu
      vmClass: best-effort-large
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 100Gi
