#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: #@ data.values.tap.view.ingress.tls_namespace
spec:
  delegations:
    - secretName: #@ data.values.tap.view.ingress.tls_secret
      targetNamespaces:
        - "*"
    - secretName: #@ "learning-center-{}".format(data.values.tap.view.ingress.tls_secret)
      targetNamespaces:
        - "*"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ data.values.tap.view.ingress.tls_secret
  namespace: #@ data.values.tap.view.ingress.tls_namespace
spec:
  commonName: #@ "*.{}".format(data.values.tap.view.ingress.domain)
  dnsNames:
  - #@ "*.{}".format(data.values.tap.view.ingress.domain)
  issuerRef:
    name: letsencrypt-contour-cluster-issuer
    kind: ClusterIssuer
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: #@ data.values.tap.view.ingress.tls_secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ "learning-center-{}".format(data.values.tap.view.ingress.tls_secret)
  namespace: learningcenter
spec:
  commonName: #@ "*.learning-center.{}".format(data.values.tap.view.ingress.domain)
  dnsNames:
  - #@ "*.learning-center.{}".format(data.values.tap.view.ingress.domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: #@ "learning-center-{}".format(data.values.tap.view.ingress.tls_secret)
