#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  secret-access-key: #@ base64.encode(data.values.aws.route53.secret_key)
kind: Secret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
spec:
  acme:
    email: #@ data.values.acme.email
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: #@ data.values.aws.region
            hostedZoneID: #@ data.values.aws.route53.zone_id
            accessKeyID: #@ data.values.aws.route53.access_key
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key

