#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: #@ data.values.tap.developer.namespace
  annotations:
    tekton.dev/git-0: #@ data.values.gitops_repository.server_address
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.gitops_repository.owner
  password: #@ data.values.gitops_repository.access_token